PLAYERS_FILE = "players.csv"
PLAYERS_AMOUNT = 10000
MIN_YEAR_BIRTH = 1985
MAX_YEAR_BIRTH = 2005
MIN_MMR = 5000
MAX_MMR = 10000

TEAMS_FILE = "teams.csv"
TEAMS_AMOUNT = 1000
MIN_YEAR_TEAM = 2005
MAX_YEAR_TEAM = 2021
MAX_DURATION = 30    
MIN_EARNINGS = 1e3
MAX_EARNINGS = 1e7

TOURNAMENTS_FILE = "tournaments.csv"
TOURNAMENTS_AMOUNT = 1000
MIN_PRIZE = 1e5
MAX_PRIZE = 4e7
MIN_YEAR_EVENT = 2005
MAX_YEAR_EVENT = 2021

COMPANIES_FILE = "companies.csv"
COMPANIES_AMOUNT = 1000
MIN_REVENUE = 1e3
MAX_REVENUE = 1e6

TEAM_PLAYER_FILE = "teams_players.csv"
PLAYERS_PER_TEAM = 5

COMPANIES_TOURNAMENTS_FILE = "companies_tournaments.csv"
MIN_SPONSORS = 5
MAX_SPONSORS = 50
MIN_DEPOSIT = 1e4
MAX_DEPOSIT = 1e6

COMPANIES_TEAMS_FILE = "companies_teams.csv"

TOURNAMENTS_TEAMS_FILE = "tournaments_teams.csv"

COUNTRIES_FILE = "countries.txt"
HEROES_FILE = "heroes_list.txt"
ROLES_FILE = "roles.txt"
CITIES_FILE = "cities.txt"
REGIONS_FILE = "regions.txt"


MIN_TIER = 1
MAX_TIER = 4
